version: '2'
services:
  app:
    build: .
    command: sidekiq
    volumes:
      - .:/app
    links:
      - redis
      - db
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: 'redis://redis:6379/12'
  web:
    build: .
    command: 'rails s -b 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - redis
      - db
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: 'redis://redis:6379/12'
  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
